# Generated by Django 3.2.5 on 2022-01-24 16:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20220125_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_num', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('cre_date', models.TimeField(default=datetime.datetime(2022, 1, 25, 1, 4, 31, 842563))),
                ('board_type', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user')),
            ],
            options={
                'db_table': 'board',
                'managed': True,
            },
        ),
    ]
