# Generated by Django 3.2.5 on 2022-01-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cre_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
