# Generated by Django 2.2.5 on 2022-01-25 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cre_date',
            field=models.TimeField(default=datetime.datetime(2022, 1, 25, 16, 59, 19, 705601)),
        ),
    ]
