# Generated by Django 3.2.5 on 2022-01-25 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220125_0017'),
        ('bungae', '0002_auto_20220125_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BungaeBoard',
            fields=[
                ('board_num', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('cre_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
