# Generated by Django 3.2.5 on 2022-01-25 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220125_0017'),
        ('bungae', '0003_auto_20220125_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungaeboard',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
