# Generated by Django 3.2.5 on 2022-01-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0006_rename_nickname_bungaeboard_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bungaeboard',
            old_name='board_num',
            new_name='bungae_num',
        ),
    ]
