# Generated by Django 3.2.5 on 2022-01-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0007_rename_board_num_bungaeboard_bungae_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bungaeboard',
            old_name='User',
            new_name='user_id',
        ),
    ]
