# Generated by Django 3.2.5 on 2022-01-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0008_rename_user_bungaeboard_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bungaeboard',
            old_name='user_id',
            new_name='User',
        ),
    ]
