# Generated by Django 3.2.5 on 2022-01-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0009_rename_user_id_bungaeboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungaeboard',
            name='cre_date',
            field=models.TextField(),
        ),
    ]
