# Generated by Django 3.2.5 on 2022-01-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0010_alter_bungaeboard_cre_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungaeboard',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bungaeboard',
            name='cre_date',
            field=models.TextField(null=True),
        ),
    ]
