# Generated by Django 3.2.5 on 2022-01-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0011_auto_20220125_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungaeboard',
            name='bungae_num',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
