# Generated by Django 3.2.5 on 2022-01-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0015_alter_bungaeboard_bungae_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bungaeboard',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='bungaeboard',
            table='bungaeboard',
        ),
    ]
