# Generated by Django 3.2.5 on 2022-01-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0016_auto_20220125_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungaeboard',
            name='cre_date',
            field=models.DateTimeField(null=True),
        ),
    ]
