# Generated by Django 3.2.5 on 2022-01-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0017_alter_bungaeboard_cre_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bungaeboard',
            name='post_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bungaeboard',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
