# Generated by Django 3.2.5 on 2022-01-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0018_auto_20220126_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bungaeboard',
            options={'managed': False},
        ),
    ]
