# Generated by Django 3.2.5 on 2022-01-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungae', '0019_alter_bungaeboard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_pw', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
