# Generated by Django 3.2.5 on 2022-01-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20220125_1451'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
