# Generated by Django 3.2.5 on 2022-01-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20220125_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usergame',
            fields=[
                ('user_game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_game_title', models.CharField(max_length=50)),
                ('user_game_content', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_game',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
