# Generated by Django 3.2.5 on 2022-01-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220125_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_title', models.CharField(max_length=50)),
                ('game_content', models.CharField(max_length=255)),
                ('game_img', models.CharField(max_length=255)),
                ('game_detail', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
    ]
