# Generated by Django 3.2.5 on 2022-01-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieQuiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('initial', models.CharField(max_length=100, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'movie_quiz',
                'managed': False,
            },
        ),
    ]
