# Generated by Django 2.2.5 on 2022-01-25 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220125_0017'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('user_game_id', models.IntegerField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('user_game_title', models.CharField(max_length=50)),
                ('user_game_content', models.TextField()),
                ('user_game_img', models.ImageField(upload_to='')),
                ('date_time', models.DateTimeField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user')),
            ],
            options={
                'db_table': 'user_game',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='game',
        ),
    ]
