# Generated by Django 4.0.1 on 2022-01-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20220125_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_pw', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
    ]
