# Generated by Django 4.0.1 on 2022-01-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20220126_1733'),
        ('recommendation', '0003_user_alter_post_options'),
    ]

    operations = [
    ]
