# Generated by Django 3.2.5 on 2022-01-27 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20220126_1733'),
        ('recommendation', '0003_user_alter_post_options'),
    ]

    operations = [
    ]
