# Generated by Django 3.2.5 on 2022-01-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_merge_20220127_1055'),
        ('recommendation', '0004_merge_20220127_1056'),
    ]

    operations = [
    ]
